const jobs = [
  { id: 1, title: "Frontend Developer", company: "ABC Corp", sallary: "5 LPA", job_type: "Full-time" },
  { id: 2, title: "Backend Developer", company: "XYZ Ltd", sallary: "7 LPA", job_type: "Part-time" },
  { id: 3, title: "Full Stack Developer", company: "Tech Solutions", sallary: "10 LPA", job_type: "Full-time" },
  { id: 4, title: "Data Scientist", company: "Innovatech", sallary: "12 LPA", job_type: "Part-time" },
  { id: 5, title: "QA Engineer", company: "DataWorks", sallary: "8 LPA", job_type: "Full-time" },
  { id: 6, title: "Project Manager", company: "SoftLabs", sallary: "9 LPA", job_type: "Part-time" },
  { id: 7, title: "Product Manager", company: "CloudNet", sallary: "15 LPA", job_type: "Full-time" },
  { id: 8, title: "DevOps Engineer", company: "WebGear", sallary: "6 LPA", job_type: "Part-time" },
  { id: 9, title: "UX Designer", company: "CodeCraft", sallary: "11 LPA", job_type: "Full-time" },
  { id: 10, title: "Mobile App Developer", company: "NextGen", sallary: "14 LPA", job_type: "Part-time" },

  { id: 11, title: "Frontend Developer", company: "ABC Corp", sallary: "5 LPA", job_type: "Full-time" },
  { id: 12, title: "Backend Developer", company: "XYZ Ltd", sallary: "7 LPA", job_type: "Part-time" },
  { id: 13, title: "Full Stack Developer", company: "Tech Solutions", sallary: "10 LPA", job_type: "Full-time" },
  { id: 14, title: "Data Scientist", company: "Innovatech", sallary: "12 LPA", job_type: "Part-time" },
  { id: 15, title: "QA Engineer", company: "DataWorks", sallary: "8 LPA", job_type: "Full-time" },
  { id: 16, title: "Project Manager", company: "SoftLabs", sallary: "9 LPA", job_type: "Part-time" },
  { id: 17, title: "Product Manager", company: "CloudNet", sallary: "15 LPA", job_type: "Full-time" },
  { id: 18, title: "DevOps Engineer", company: "WebGear", sallary: "6 LPA", job_type: "Part-time" },
  { id: 19, title: "UX Designer", company: "CodeCraft", sallary: "11 LPA", job_type: "Full-time" },
  { id: 20, title: "Mobile App Developer", company: "NextGen", sallary: "14 LPA", job_type: "Part-time" },

  { id: 21, title: "Frontend Developer", company: "ABC Corp", sallary: "5 LPA", job_type: "Full-time" },
  { id: 22, title: "Backend Developer", company: "XYZ Ltd", sallary: "7 LPA", job_type: "Part-time" },
  { id: 23, title: "Full Stack Developer", company: "Tech Solutions", sallary: "10 LPA", job_type: "Full-time" },
  { id: 24, title: "Data Scientist", company: "Innovatech", sallary: "12 LPA", job_type: "Part-time" },
  { id: 25, title: "QA Engineer", company: "DataWorks", sallary: "8 LPA", job_type: "Full-time" },
  { id: 26, title: "Project Manager", company: "SoftLabs", sallary: "9 LPA", job_type: "Part-time" },
  { id: 27, title: "Product Manager", company: "CloudNet", sallary: "15 LPA", job_type: "Full-time" },
  { id: 28, title: "DevOps Engineer", company: "WebGear", sallary: "6 LPA", job_type: "Part-time" },
  { id: 29, title: "UX Designer", company: "CodeCraft", sallary: "11 LPA", job_type: "Full-time" },
  { id: 30, title: "Mobile App Developer", company: "NextGen", sallary: "14 LPA", job_type: "Part-time" },
];

export default jobs;
